const Redis = require('ioredis');
const logger = require('../utils/logger');
const redisConfig = { host: process.env.REDIS_HOST || 'localhost', port: parseInt(process.env.REDIS_PORT) || 6379, password: process.env.REDIS_PASSWORD || undefined, db: parseInt(process.env.REDIS_DB) || 0, retryStrategy: (times) => Math.min(times * 100, 3000), lazyConnect: true };
const client = new Redis(redisConfig);
const subscriber = new Redis(redisConfig);
client.on('connect', () => logger.info('Redis: connected'));
client.on('error', (err) => logger.error('Redis error', { error: err.message }));
subscriber.on('error', (err) => logger.error('Redis subscriber error', { error: err.message }));
const OTP_TTL = parseInt(process.env.OTP_EXPIRES_MINUTES || 10) * 60;
const setOTP = (phone, otp) => client.setex(`otp:${phone}`, OTP_TTL, otp);
const getOTP = (phone) => client.get(`otp:${phone}`);
const deleteOTP = (phone) => client.del(`otp:${phone}`);
const setCache = (key, value, ttlSeconds = 60) => client.setex(key, ttlSeconds, JSON.stringify(value));
const getCache = async (key) => { const raw = await client.get(key); return raw ? JSON.parse(raw) : null; };
const deleteCache = (key) => client.del(key);
const PRICE_CHANNEL = 'bse:prices';
const publishPrices = (priceMap) => client.publish(PRICE_CHANNEL, JSON.stringify(priceMap));
const subscribePrices = (handler) => { subscriber.subscribe(PRICE_CHANNEL); subscriber.on('message', (channel, message) => { if (channel === PRICE_CHANNEL) { try { handler(JSON.parse(message)); } catch(e) {} } }); };
const connect = async () => { await client.connect(); await subscriber.connect(); logger.info('Redis: all clients connected'); };
module.exports = { client, subscriber, connect, setOTP, getOTP, deleteOTP, setCache, getCache, deleteCache, publishPrices, subscribePrices };
