const router = require('express').Router();
const rateLimit = require('express-rate-limit');
const authLimiter = rateLimit({ windowMs: 15*60*1000, max: 10 });
const apiLimiter = rateLimit({ windowMs: 60*1000, max: 120 });
const auth = require('../controllers/auth.controller');
const tokens = require('../controllers/tokens.controller');
const portfolio = require('../controllers/portfolio.controller');
const orders = require('../controllers/orders.controller');
const watchlist = require('../controllers/watchlist.controller');
const alerts = require('../controllers/alerts.controller');
const notifs = require('../controllers/notifications.controller');
const beej50 = require('../controllers/beej50.controller');
const { authenticate } = require('../middleware/auth');
router.post('/auth/send-otp', authLimiter, auth.sendOTPValidation, auth.sendOTP);
router.post('/auth/verify-otp', authLimiter, auth.verifyOTPValidation, auth.verifyOTP);
router.post('/auth/refresh', auth.refreshToken);
router.get('/auth/me', authenticate, auth.getMe);
router.get('/tokens', apiLimiter, tokens.listTokens);
router.get('/tokens/:symbol', apiLimiter, tokens.getToken);
router.get('/tokens/:symbol/price-history', apiLimiter, tokens.getPriceHistory);
router.get('/tokens/:symbol/order-book', apiLimiter, tokens.getOrderBook);
router.get('/tokens/:symbol/trades', apiLimiter, tokens.getRecentTrades);
router.get('/beej50', apiLimiter, beej50.getIndex);
router.get('/beej50/history', apiLimiter, beej50.getHistory);
router.get('/portfolio', authenticate, portfolio.getPortfolio);
router.get('/portfolio/transactions', authenticate, portfolio.getTransactions);
router.post('/orders', authenticate, orders.placeOrderValidation, orders.placeOrder);
router.get('/orders', authenticate, orders.getOrders);
router.delete('/orders/:id', authenticate, orders.cancelOrder);
router.get('/watchlist', authenticate, watchlist.getWatchlist);
router.post('/watchlist', authenticate, watchlist.addToWatchlist);
router.delete('/watchlist/:symbol', authenticate, watchlist.removeFromWatchlist);
router.get('/alerts', authenticate, alerts.getAlerts);
router.post('/alerts', authenticate, alerts.createAlertValidation, alerts.createAlert);
router.delete('/alerts/:id', authenticate, alerts.deleteAlert);
router.get('/notifications', authenticate, notifs.getNotifications);
router.patch('/notifications/read-all', authenticate, notifs.markAllRead);
router.patch('/notifications/:id/read', authenticate, notifs.markRead);
router.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
module.exports = router;
