const WebSocket = require('ws');
const { query } = require('../config/database');
const { publishPrices } = require('../config/redis');
const logger = require('../utils/logger');
const TICK_INTERVAL = parseInt(process.env.WS_PRICE_TICK_INTERVAL_MS||3000);
function send(ws, type, data){ if(ws.readyState===WebSocket.OPEN) ws.send(JSON.stringify({type,data,ts:Date.now()})); }
function createPriceServer(httpServer){ const wss = new WebSocket.Server({server:httpServer,path:'/ws'}); const subscriptions = new Map(); const clients = new Set(); const priceCache = new Map();
wss.on('connection',(ws,req)=>{ ws.isAlive=true; ws.subs=new Set(); clients.add(ws); ws.on('pong',()=>{ws.isAlive=true;}); ws.on('message',async(raw)=>{ let msg; try{msg=JSON.parse(raw);}catch{return;} if(msg.type==='subscribe'){ const symbols=Array.isArray(msg.symbols)?msg.symbols:[msg.symbols]; for(const sym of symbols){ const r=await query('SELECT id FROM crop_tokens WHERE symbol=$1',[sym.toUpperCase()]); if(!r.rows.length)continue; const tid=r.rows[0].id; ws.subs.add(tid); if(!subscriptions.has(tid))subscriptions.set(tid,new Set()); subscriptions.get(tid).add(ws); } send(ws,'subscribed',{symbols}); } else if(msg.type==='subscribe_all'){ const {rows}=await query("SELECT id FROM crop_tokens WHERE status='active'"); for(const t of rows){ ws.subs.add(t.id); if(!subscriptions.has(t.id))subscriptions.set(t.id,new Set()); subscriptions.get(t.id).add(ws); } send(ws,'subscribed_all',{count:rows.length}); } else if(msg.type==='ping'){ send(ws,'pong',{}); } }); ws.on('close',()=>{ clients.delete(ws); for(const tid of ws.subs){ subscriptions.get(tid)?.delete(ws); } }); });
const heartbeat = setInterval(()=>{ for(const ws of clients){ if(!ws.isAlive){ws.terminate();continue;} ws.isAlive=false; ws.ping(); } },30000);
const ticker = setInterval(async()=>{ try{ const {rows}=await query("SELECT id,symbol,current_price_inr,prev_close_inr FROM crop_tokens WHERE status='active'"); const priceMap={}; for(const t of rows){ const prev=priceCache.get(t.id)||parseFloat(t.current_price_inr); const noise=(Math.random()-0.5)*prev*0.004; const newPrice=Math.max(prev*0.9,prev+noise); priceCache.set(t.id,newPrice); const change_pct=((newPrice-parseFloat(t.prev_close_inr))/parseFloat(t.prev_close_inr)*100).toFixed(2); priceMap[t.symbol]={price:newPrice.toFixed(4),change_pct}; const subs=subscriptions.get(t.id); if(subs?.size){ const msg=JSON.stringify({type:'price_update',data:{symbol:t.symbol,price:newPrice.toFixed(4),change_pct},ts:Date.now()}); for(const ws of subs){ if(ws.readyState===WebSocket.OPEN)ws.send(msg); } } } const tickerMsg=JSON.stringify({type:'ticker',data:priceMap,ts:Date.now()}); for(const ws of clients){ if(ws.readyState===WebSocket.OPEN)ws.send(tickerMsg); } await publishPrices(priceMap); }catch(err){logger.error('Price tick error',{error:err.message});} },TICK_INTERVAL);
wss.on('close',()=>{ clearInterval(heartbeat); clearInterval(ticker); });
logger.info('WebSocket price server started',{path:'/ws'}); return wss; }
module.exports = { createPriceServer };
